version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - /srv/db/nextcloud:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - stack.env

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    build: ./app
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - stack.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: unless-stopped
    ports:
      - 10.137.137.2:80:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    build: ./app
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    cap_add: [ SYS_NICE ]
    depends_on:
      - db
      - redis
  
  smb-games:
    image: dperson/samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      /mnt/smb/games:/mnt:
    command: '-m 512m -s "Games Share;/mnt;yes,no,no,user" -u user;$SMB_PASSWORD -p'

volumes:
  nextcloud:
  db:
